language: java

jdk: openjdk8

addons:
  sonarcloud:
    organization: lorenzobettini-github
    token:
      secure: $SONAR_TOKEN

install: true

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache

env:
  - DISPLAY=:99.0

before_script:
 - sh -e /etc/init.d/xvfb start

script:
- ./mvnw clean verify -Pjacoco
- ./mvnw verify -Pe2e-tests
- ./mvnw coveralls:report sonar:sonar
