language: java

dist: xenial

jdk: openjdk8

git:
  depth: false

addons:
  sonarcloud:
    organization: lorenzobettini-github

services:
  - xvfb

install: true

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache

script:
- ./mvnw clean verify -Pjacoco
- ./mvnw verify -Pe2e-tests
- ./mvnw coveralls:report sonar:sonar
