language: java

jdk: openjdk8

addons:
  sonarcloud:
    organization: lorenzobettini-github
    token:
      secure: $SONAR_TOKEN

install: true

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache

script:
- ./mvnw clean verify -Pjacoco coveralls:report sonar:sonar
