sudo: required

language: java

jdk: oraclejdk8

addons:
  apt:
    update: true
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sonarcloud:
    branches:
      - sonarcloud
      - master
    organization: "lorenzobettini-github"
    token:
      secure: "E1QRRGdZeBwy0isOWt2/8k5yWNwBxI0JIonA7OhjUvAUZ/CQ1wGQW8SaxK4fmEln7oRiog9QKnxdUVsvmSBD9u05Gu0J8avXcFohBk2mO3hq+t1pH991priqU07Ga4OO7OpsfmMYsHOJ1X5LNAmsvgyXg5PbgKXwg4JFYaX+9QotUgVOCFdZhWv2EQATzOhN+XD21f7H0vuQk+A5PUaXS1VuwJ9aTMpf681HyLIUlImQpaZlsV/VuK+SxR+jSrSZbdd9H6B8ZpyMNB3Mh3zSMBogTlHeixbUFtpocnyHj5fUTQsrFUe6u86Hsv0CqEnuVEuQpipZUIxrcJLJ0riexqXv1ksNnX7olbO1kGml3deT5QUWsvoV0q7wMCysvuX01jV+f23rnfPzyMYVb3zGmU4HrlnbNhe/GtC0c/rGUFhTQam4l8AVFMUQxFYju9dJVMtFLDao1LxCgQN71NaHTL/mX7Uzf0uL1i4aBItt8HldPONb8AeVGffxAl3LZ53tBvdBHP+XoQlsxSiBEoeu5H3Ie9Lsvp5/PW25o36An1fzBLtutw1dXidTVMXiS/4UAmTou6TepZVO5xG0piT2a0Ag4JpSLOm7IZ/OJAktZA/YjZIOVlycpdA1eObRLCce2WRA3CHHxkagjZvoFElOuFcwP6lVy0VEpXbyhic9d/A="
    github_token:
      secure: "Y5+YHSKH20sxsmXRP2P+cJCjEMJtrr331KYiVgvQ4UtcnLxEveL8WNv6bcdGSylJMEYnC3GhEHIcY6OATy4fgoCjxoNg/mNOGejifve45wfd/RZ3xIB95daTJOeKG1XuC8G2culVDWjP4Pt8sh7Sm4jsFpZvZlNrAcycvqjraMkwyHepeGQbNpUNJnEpZQLw/fIVulqmbeyjxtwrxtjwqOpwg1RQp0bnJ39LlSsFGfUdaZhVJU6DUSvfYgpchmZrvBA/DoAcBJDlZ46FFsBRP72nSupTka2Y6A/Cl0s26pLoSc8zKpNOZY5A92eZCcI5CRszX8EQIqMcIy7yj40mTk5T9vW7puwGbeHLmzThD2D0e/RRfWg3AfmKr8YkHQzggarbxv8PLe1hdctkFBvCijOmLOi2Ii4gshut/aRb1HDlcg/hlsc4N0BYGUPtlGWwrDpFwne0SFQPwBHh/2Z5J9E+HihVJSR/Yke6BVpDjjHo8Won/NJ4GRz63k1hKuCpNpJVKh6MDHurdx42nTdvVlyBrLRhf2rhQNf4d8jmMw5xJMEx+jpSpIWFBhkAbabmtl1WbevKSKt0fE+Dp/ROOX1Asrl45WRci3M2glfDSEH05k+XbiAJc5Edqw9s/+zjNoSJwFSDtP3+F5zVH19rh6pWYiO7SF1bjI+CH3dOMoo="

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.sonar/cache'

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install: true

script:
 - export
 - cd demo-spring-testing
 - ./mvnw clean verify -Pjacoco coveralls:report sonar:sonar
 - ./mvnw verify -Pe2e-tests

