sudo: false

language: java

jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

install: true

script:
 - cd demo-spring-testing
 - ./mvnw clean verify -Pjacoco coveralls:report
 - ./mvnw verify -Pe2e-tests

