language: java

dist: xenial

jdk: openjdk8

git:
  depth: false

addons:
  sonarcloud:
    organization: lorenzobettini-github

install: true

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache

script:
- ./mvnw clean verify -Pjacoco coveralls:report sonar:sonar
